nginx:
  image: nginx:1.11
  container_name: nginx
  volumes:
   - ${HOME_DIR}/nginx/static:/system/static
   - ${HOST_SSL_DIR}:/hs-certs 
   - ${HS_LOG_FILES}:/var/log/nginx 
   - ${HOME_DIR}/nginx/docker-entrypoint.sh:/docker-entrypoint.sh
   - ${HOME_DIR}/nginx/config-files/hs-nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
   - "443:443"
#  command: ["/docker-entrypoint.sh"]   
